log:
  level: INFO
  filePath: "/traefik_logs/api.log"

accessLog:
  filePath: "/traefik_logs/access.log"

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "todd.develop@gmail.com"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(``)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: backend-trfine-production
      priority: 1
      tls:
        certResolver: letsencrypt

    media-router:
      rule: "Host(``) && PathPrefix(`/media`)"
      entryPoints:
        - web-secure
      service: nginx_media
      priority: 3
      tls:
        certResolver: letsencrypt

  services:
    backend-trfine-production:
      loadBalancer:
        servers:
          - url: http://backend-trfine-production:5000

    nginx_media:
      loadBalancer:
        servers:
          - url: http://nginx-media

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
